### ISSUE TITLE
Produto x Quantidade x Custo

### ISSUE THREAD

**Issue by pauloroncarati** [DisciplinasProgramacao/lpm-projeto1-grupo6#7]
Devemos considerar que um produto pode ter mais de um preço de custo?

Exemplo:

Lote 1 | Produto A | 10 unidades | R$ 10,00
Lote 2 | Produto A | 05 unidades | R$ 15,00
...
Lote N | Produto A | 00 unidades | R$ 00,00

**Comment by pauloroncarati** [comment]
Vou considerar que não, pois isso traria problemas na hora de realizar uma possível venda

**Comment by joaocaram** [comment]
Paulo, não, o produto tem um mesmo  preço para qualquer unidade/quantidade.
Se chegar ao ponto de implementar esta regra, provavelmente precisaremos de
outras classes.

Att,
João
